name: Daily LinkedIn AI Post

on:
  schedule:
    - cron: '30 3 * * *'  # 03:30 UTC = 09:00 IST daily
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run daily LinkedIn post
        env:
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
          PROFILE_URN: ${{ secrets.PROFILE_URN }}
        run: |
          python daily_linkedin_ai_news.py
